name = "uedong"
license = ""
licenselink = ""
description = ""
homepage = "https://uedog.com"
tags = ["blog"]
features = ["grid view"]
min_version = "0.65.0"

[author]
    name = "Terry.Wang"
    homepage = "https://terry.wang/"
